### PR TITLE
initial commit for data format

### PR DESCRIPTION
**Pull request by feomike**
adding the version 0.01 of the data format.  this is the format we would a) ask others to submit data to us in, and b) ingest directly into ES.

### CODE REVIEW

**Comment by jmarin** [comment]
@feomike A suggestion, can we put this inside a specs or docs folder? I see more coming and that will help with keeping things clean. We can link to them from main README later so they don't get lost

**Comment by feomike** [comment]
@jmarin i know right?  i hit the pull request button right as that same thought came to me.  whats the best method?  issue a new pull request, with the document moved?

**Comment by jmarin** [comment]
@feomike You can just create the folder, move the doc and commit on **your** master branch and push to your fork. The pull request should get updated

**Comment by feomike** [comment]
@jmarin so created and moved.

**Pull request merged**
