### PR TITLE
Use local ES for test-harness & upgrade to ES 2.2 w/ Shield

### LINKED ISSUE #209: Move test-harness's Elasticsearch setup from Docker Compose to local install
Elasticsearch performance is very poor when running under our development Docker Machine VirtualBox setup.  This is primarily due to VirtualBox's slow I/O, which is a _reaaaally_ painful when pushing many gigs worth of address data at it, as we need to do for using the test-harness.

To get around this, let's move Elasticsearch out of Docker Compose, and run it locally instead.  In initial testing, I've been able to load all points data in about 30 minutes, which beats several hours under the Docker setup.

This fix will also include the upgrade to Elasticsearch 2.2, making this dependent on PR #206.

### PR DESCRIPTION
**Pull request by hkeeler**
Closes #209

This PR is primarily intended to refactor the Docker Compose configuration for the test-harness, using a locally running Elasticsearch instance, rather than one in Docker due to VirtualBox's slow I/O.  However, I did not want to come back to this as soon as we upgraded to ES 2.2, so I've merged in the work @chosak did on #206, and then added a few additional fixups to get it all running.

A few of these "fixes" need further research, like:
- Why do we _now_ need fully-qualified field names in queries, when we didn't before.
- Why does `matchPhraseQuery` no longer work for street names?  I've switched this to `matchQuery`.

I also discovered bugs in the Census geocoder unrelated to the ES upgrade.  There will be follow-up issues for both grasshopper and grasshopper-loader coming soon with more details on these fixes.  In the meantime, I have commented out the `houseQuery` portion of the filter.  This means the Census geocoder now returns results, but they are pretty inaccurate.

I have **not** changed the standard Docker Compose setup, keeping ES as a Docker container.  I don't think we'll be using a full dataset when running this setup, so it seemed better to keep it simple.  If we decide we need this external ES setup across-the-board, it'll be a pretty simple fix.

I think this PR now replaces #206 as it has all of its changes, plus more.  However, there's a lot of good conversation over on that issue, so please check it out as well while reviewing this one.

### CODE REVIEW

**Comment by chosak** [comment]
The changes pulled in from #206 look good to me. As you mentioned over there it'd be nice to pull out the client builder stuff into a utility function, as that code's now repeated in several places.

Regarding fully-qualified field names, see [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_fields_cannot_be_referenced_by_short_name) comment in the 2.0 breaking changes notes.

I dug a bit into `matchPhraseQuery` but couldn't find any obvious 2.0+ change that would have modified this behavior.

**Comment by hkeeler** [comment]
@chosak, thanks for checking this out, and for the link about how references to nested fields changed.

**Comment by hkeeler** [comment]
I've created issue #212 and #213 for tracking outstanding issues from this PR.

**Comment by hkeeler** [comment]
I think the `test_harness` docs are in pretty good shape.  I'm taking down the "do not merge" sign.  The PR is now ready for full review.

If you'd like to check out the docs rendered form, head over to:
- https://github.com/hkeeler/grasshopper/tree/compose-test-harness-fix/test-harness

**Pull request merged**
