### PR TITLE
Container Monitoring: cAdvisor / InfluxDB / Grafana

### PR DESCRIPTION
**Pull request by hkeeler**
Here's an initial working version of cAdvisor / InfluxDB / Grafana setup for capturing container metrics.  I'm pleasantly surprised at how well it works.  I _generally_ followed the instructions laid out on:
- https://www.brianchristner.io/how-to-setup-docker-monitoring/

Once issue I haven't worked through is that the InfluxDB does not recover from a `docker-compose stop`.  You must do a full `docker-compose rm influxdb` before doing an `up`.  Not sure what up here, but I'll work it out.

Also, the Grafana setup is not included.  You'll need to follow the above-mentioned doc to see the graphs.  I _should_ be able to get some base visualizations into the image, though, since Grafana has a import/export for dashboards.  I'll play with that more on Monday.

### CODE REVIEW

**Comment by hkeeler** [comment]
Here's a sample of CPU, memory, and network stats for all containers in the stack.  Its pretty simple (though tedious) to setup.  Currently each line is its own query.  I'm hoping to find a smarter, more dynamic, less resource intensive way of setting this up. 

screen shot 2015-06-15 at 2 51 40 pm

**Comment by hkeeler** [comment]
The question came up earlier about whether or not we can adjust the frequency at which cAdvisor sends its stats.  Indeed, it does have a `--housekeeping_interval=1s` runtime option.  Here's the rest of the runtime options:
- https://github.com/google/cadvisor/blob/master/docs/runtime_options.md

**Comment by hkeeler** [comment]
This is now available for code review.  Enjoy!

**Comment by hkeeler** [comment]
Please hold off on merging this.  This PR is going to need some fixin' now that #117 has been merged in.

**Comment by jmarin** [comment]
Hi @hkeeler I'm reviewing the PR, it looks good but when trying it I wasn't able to get Grafana graphs to work. They seem to be defined, but I get the following on every panel

screen shot 2015-08-03 at 9 03 08 am

Clicking on the exclamation point produces the following definition for the query.

screen shot 2015-08-03 at 9 03 18 am

Thoughts?

**Comment by hkeeler** [comment]
Hmmm.  Grafana is very touchy when it comes to its configuration, and the true error is not always related to what you see when you click on the little red exclamation.

Let me build from scratch and see if I get the same result.

**Comment by hkeeler** [comment]
This is occurring because Grafana (by default) caches the values in those dropdown, so you're seeing some old values from one of my last runs.

The quick fix is to set "Refresh on Load" option for the `container_id` template:
1. Go to "JVM Metrics Detail" dashboard.
2. Click little _gear_ icon at the top.
3. Click "Edit" next to "$containder_id"
4. Check "Refresh on Load".
5. Hit "Update"
6. Refresh dashboard with button in upper right.

I am going to try to make this change and push up an updated version of the `grafana.db` file.  These values all get dumped into the "dashboard" table there in a giant JSON blob.

**Comment by hkeeler** [comment]
Oh yeah, using "Refresh on Load" could cause a performance hit.  It definitely does for the _cAdvisor_ data.  However, _Metrics_ structures their data in InfluxDB much better, so it may not be an issue here.  We'll have to keep an eye on it.

**Comment by hkeeler** [comment]
@jmarin, should be good-to-go now.  Take it for another spin, and let me know.

**Pull request merged**
